@EnrollmentService_HostAddress = http://127.0.0.1:8085
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImJlY2E4N2Y1LWRhNTktNDIwZC1iMmYxLTQzMTQ2YmZjODEyZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJWaWpheSBLdW1hciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InBtZGhyczRAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsImV4cCI6MTc3NzExODA2OSwiaXNzIjoiSWRlbnRpdHlTZXJ2aWNlIiwiYXVkIjoiSWRlbnRpdHlTZXJ2aWNlQ2xpZW50cyJ9.pF4IwNkYjbpb5QfNjXEUw2kn9nU2FuUztzq6Bp6Lid4
@CourseId = d7826501-3c46-42c3-a3cc-1113960a1532
@EnrollmentId = 6675e5d4-e0c7-4f1f-a7c6-59809d113af8

### [STUDENT] Enroll in a Course
# Access: Any authenticated user (typically Student role).
# Usage: Provide a valid CourseId from the CourseService to join the course.
# Note: The StudentId is automatically extracted from your JWT Token.
# NEW: This request now triggers an asynchronous email notification via RabbitMQ.
# Check Mailhog (http://localhost:8025) to see the sent email.
POST {{EnrollmentService_HostAddress}}/api/Enrollment
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "courseId": "{{CourseId}}"
}

### [STUDENT] Get My Enrollments
# Access: Any authenticated student.
# Usage: Use this to see all courses you are currently enrolled in.
GET {{EnrollmentService_HostAddress}}/api/Enrollment/my-enrollments
Authorization: Bearer {{Token}}

### [STUDENT / ADMIN] Get Enrollment Details
# Access: 
#   1. The specific Student who owns this enrollment record.
#   2. Any user with an 'Admin' role.
# Usage: Replace {{EnrollmentId}} with a GUID returned from the 'Get My Enrollments' request.
GET {{EnrollmentService_HostAddress}}/api/Enrollment/{{EnrollmentId}}
Authorization: Bearer {{Token}}
