@IdentityService_HostAddress = http://localhost:8001

### [ANYONE] Register Admin User
# Used by: New Administrators to set up system access
POST {{IdentityService_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "name": "Admin User",
  "email": "admin@example.com",
  "password": "Password123!",
  "role": "Admin"
}

### [ANYONE] Register Instructor User
# Used by: Subject matter experts to create and manage courses
POST {{IdentityService_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "name": "Instructor User",
  "email": "instructor@example.com",
  "password": "Password123!",
  "role": "Instructor"
}

### [ANYONE] Register Student User
# Used by: Learners to enroll and view course content
POST {{IdentityService_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "name": "Student1",
  "email": "student1@gmail.com",
  "password": "Student1@123",
  "role": "Student"
}


### [ANYONE] Login Admin User
# Returns: JWT Token for Admin actions
POST {{IdentityService_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Password123!"
}

### [ANYONE] Login Instructor User
# Returns: JWT Token for Instructor actions (Course creation, lesson management)
POST {{IdentityService_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "instructor@example.com",
  "password": "Password123!"
}

### [ANYONE] Login Student User
# Returns: JWT Token for Student actions (Viewing courses, enrollment)
POST {{IdentityService_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "student1@gmail.com",
  "password": "Student1@123"
}

### [ANYONE] Google Login
# Returns: JWT Token for users authenticated via Google
POST {{IdentityService_HostAddress}}/api/Auth/google-login
Content-Type: application/json

{
  "idToken": "YOUR_GOOGLE_ID_TOKEN_HERE"
}

### [AUTHORIZED] Test Secure Endpoint
GET {{IdentityService_HostAddress}}/api/Auth/secure
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjdmMDVmMjJkLWUzYmUtNDEzNy1iMjQwLWFmZmI0ZjRmMjdmOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJBZG1pbiBVc2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3NzE1OTU2OSwiaXNzIjoiSWRlbnRpdHlTZXJ2aWNlIiwiYXVkIjoiSWRlbnRpdHlTZXJ2aWNlQ2xpZW50cyJ9.fIKvYm-XkhRHUs1kwqpr-mJvFyInQllFuAGSS6JrOz8
